### ISSUE TITLE
Service Config & LoadBalancing Policy

### ISSUE THREAD

**Issue by lukaszx0** [grpc/proposal#15]
It's not the proposal, but a comment/suggestion to an existing document which predates grpc/proposal - the [service config](https://github.com/grpc/grpc/blob/master/doc/service_config.md). I thought that the issue here would be the best medium to discuss it.

```
  // Load balancing policy name.
  // Supported values are 'round_robin' and 'grpclb'.
  // Optional; if unset, the default behavior is pick the first available
  // backend.
  // Note that if the resolver returns only balancer addresses and no
  // backend addresses, gRPC will always use the 'grpclb' policy,
  // regardless of what this field is set to.
  'loadBalancingPolicy': string,
```

I find `loadBalancingPolicy` a bit limiting. First of all, it supports only `round_robin` and `grpclb`. Secondly, in the case when it's no present, it users the default of `pick_first` loadbalancer.

This basically makes it impossible to use with custom load balancer implementations that are not based on `grpclb`.

Could we relax this requirement and allow arbitrary load balancer names as well as change the default? With the default option, I'm suspecting that the documentation might be just confusing and the default won't be `pick_first` BUT what's statically set in code (eg.: in java if you set `managedChannelBuilder.loadBalancerFactory(new Foobar())` it'll be used as a fallback if servic config doesn't specify override).

@markdroth what do you think?

**Comment by markdroth** [comment]
The comment saying that the supported values are 'round_robin' and 'grpclb' is just meant to indicate that those are the only two non-default policies that are supported out of the box by the grpc code.  The value of this field is a string, and there's no reason it can't be set to whatever value you want.  If your clients are built with support for an LB policy called 'foobar', then you can use that string in the service config, and it should work.

The default is indeed to use the pick_first policy.  However, @a11r felt that we should not encourage users to explicitly set that, which is why it's not documented as a possible option.  However, if you did explicitly set it to that value, I think it should work.

**Comment by lukaszx0** [comment]
I see. Do we want to rephrase that something like:

> gRPC supports 'round_robin' and 'grpclb' but custom values are also allowed

I think it's more clear for both readers and implementers.

**Comment by mehrdada** [comment]
Looks like this issue is fixed by https://github.com/grpc/grpc/pull/10258. Closing.
